apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-gitea-path
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .IngressHost }}
      http:
        paths:
          - backend:
              service:
                name: my-gitea-http
                port:
                  number: 3000
            path: /gitea(/|$)(.*)
            pathType: ImplementationSpecific
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: my-gitea-http
                port:
                  number: 3000
            path: /gitea(/|$)(.*)
            pathType: ImplementationSpecific