apiVersion: v1
kind: Service
metadata:
  name: my-gitea-ssh
  labels:
    helm.sh/chart: gitea-9.5.1
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: my-gitea
    app.kubernetes.io/version: "1.20.5"
    version: "1.20.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: ssh
    port: 22
    targetPort: 2222
    protocol: TCP
    nodePort: 32222
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: my-gitea